version: '3.8'

services:
  my-java-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - java-app-mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - java-app-mongodb

networks:
  java-app-mongodb:

volumes:
  mongodbdata: